# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Marla's repository
tagline:          'Marla's blog'
description:      'My blog'
url:              https://daktu12.github.io
baseurl:          

author:           
  name:           'Marla Na'
  url:            https://daktu12.github.io

# Custom vars
version:          

github:           
  repo:           https://github.com/daktu12

paginate: 5
plugins: 	 				[jekyll-paginate]
paginate_path: 		'/page:num/'
